rbac:
  create: true
imagePullSecrets:
  - name: packages-cloud-lancom-de
controller:
  resources:
    limits:
      cpu: 300m
      memory: 1300Mi
    requests:
      cpu: 100m
      memory: 1300Mi
  kind: "DaemonSet"
  image:
    registry: docker.packages.cloud.lancom.de
    image: ingress-nginx/controller
    tag: "v1.11.1"
    digest: sha256:e6439a12b52076965928e83b7b56aae6731231677b01e81818bce7fa5c60161a
  allowSnippetAnnotations: true
  extraArgs:
    update-status: "true"
    update-status-on-shutdown: "false"

  config:
    enable-underscores-in-headers: "true"
    ssl-redirect: "false"
    enable-real-ip: "true"
    use-forwarded-headers: "true"
    compute-full-forwarded-for: "true"
    use-proxy-protocol: "true"
    hsts: "false"
    keep-alive: 5
    log-format-upstream: $time_local "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" $request_length $request_time [$proxy_upstream_name] [$proxy_alternative_upstream_name] $upstream_addr $upstream_response_length $upstream_response_time $upstream_status $req_id
    http-snippet: |
      map $request_uri $clean_uri {
        "~^(/cloud-service-[^/]+).*$" $1;
        default "";
      }
      map $ssl_client_s_dn $ssl_client_s_dn_cn {
        default "";
        ~CN=(?<CN>[^/,\"]+) $CN;
      }
  publishService:
    enabled: true
  service:
    annotations:
      loadbalancer.openstack.org/proxy-protocol: "true"
      loadbalancer.openstack.org/keep-floatingip: "true"
defaultBackend:
  replicaCount: 1
  enabled: true
  image:
    registry: docker.packages.cloud.lancom.de
    image: lmckube/error-pages-nginx
    tag: "s0.0.3"
  pullPolicy: Always
  port: 8080
  extraVolumeMounts:
    - name: default-be-tmp
      mountPath: /tmp
  extraVolumes:
    - name: default-be-tmp
      emptyDir: {}
