USER-SUPPLIED VALUES:
csi:
  attacherReplicaCount: 1
  provisionerReplicaCount: 1
  resizerReplicaCount: 1
  snapshotterReplicaCount: 1
longhornAdmissionWebhook:
  replicas: 1
longhornConversionWebhook:
  replicas: 1
longhornRecoveryBackend:
  replicas: 1
longhornUI:
  replicas: 1
persistence:
  defaultClass: false
  defaultClassReplicaCount: 1
  reclaimPolicy: Retain
service:
  ui:
    nodePort: 32088
    type: NodePort
