repositories:
  - name: jetstack
    url: https://charts.jetstack.io
  - name: vadimkim
    url: https://vadimkim.github.io/cert-manager-webhook-hetzner
  - name: fabmade
    url: https://fabmade.github.io/cert-manager-webhook-ionos

releases:
  - name: cert-manager
    chart: jetstack/cert-manager
    version: 1.15
    namespace: cert-manager
    values:
      - ../values/cert-manager-values.yaml
{{ if eq .Environment.Values.dnsProvider "HETZNER" }}
  - name: cert-manager-webhook-hetzner
    chart: vadimkim/cert-manager-webhook-hetzner
    version: 1.3
    namespace: cert-manager
    values:
      - ../values/cm-webhook-hetzner-values.yaml
{{ end }}
{{ if eq .Environment.Values.dnsProvider "IONOS" }}
  - name: cert-manager-webhook-ionos
    chart: fabmade/cert-manager-webhook-ionos
    version: 1.0.2
    values:
      - ../values/cm-webhook-ionos-values.yaml.yaml
{{ end }}
