repositories:
  - name: jetstack
    url: https://charts.jetstack.io
  - name: cert-manager-webhook-hetzner
    url: https://vadimkim.github.io/cert-manager-webhook-hetzner

releases:
  - name: cert-manager
    chart: jetstack/cert-manager
    version: 1.15
    namespace: cert-manager
    values:
      - ../values/cert-manager-values.yaml
  - name: cert-manager-webhook-hetzner
    chart: cert-manager-webhook-hetzner/cert-manager-webhook-hetzner
    version: 1.3
    namespace: cert-manager
    values:
      - ../values/cm-webhook-hetzner-values.yaml