repositories:
  - name: external-dns
    url: https://kubernetes-sigs.github.io/external-dns/

releases:
  - name: external-dns
    namespace: external-dns
    chart: external-dns/external-dns
    version: 1.15
    createNamespace: true
    wait: true
    values:
      - ../values/external-dns-values.yaml