repositories:
  - name: zalando
    url: https://opensource.zalando.com/postgres-operator/charts/postgres-operator

releases:
  - name: zpo
    chart: zalando/postgres-operator
    version: 1.10.1
    namespace: operator-postgres
    values:
      - ../values/postgresql-operator-values.yaml
