repositories:
  - name: strimzi
    url: https://strimzi.io/charts/
  - name: redpanda
    url: https://charts.redpanda.com

releases:
  - name: strimzi
    chart: strimzi/strimzi-kafka-operator
    namespace: operator-kafka
    version: 0.38.0
    values:
      - ../values/strimzi-values.yaml
    needs:
      - lmc-operators/strimzi-operator-crds

#  - name: lmc-kafka-console
#    chart: redpanda/console
#    version: 0.5.0
#    namespace: lmc
#    values:
#      - ../values/redpanda-console-values.yaml
